# Generated by Django 5.0.1 on 2024-03-06 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0005_mesa_total_diario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_diario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
