# Generated by Django 5.0.1 on 2024-04-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0007_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bebida',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
