# Generated by Django 5.0.1 on 2024-04-10 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0008_articulo_precio_bebida_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='bebida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurante_app.bebida'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurante_app.producto'),
        ),
    ]
