# Generated by Django 5.0.1 on 2024-04-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0010_comida_comanda_comida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='producto',
        ),
    ]
